BASE_: base.yaml

MODEL:
  META_ARCHITECTURE: FaceBaseline
  FREEZE_LAYERS: [backbone]

  BACKBONE:
    PRETRAIN: True
    PRETRAIN_PATH: /pretrain_weight.pth
    NAME: build_resnet_backbone
    LAST_STRIDE: 1
    NORM: BN
    WITH_IBN: True
    WITH_SE: True
    WITH_NL: False
    DEPTH: 101x

  HEADS:
    NAMES: FaceHead # train: clasHead, eval: EmbeddingHead
    NORM: BN
    WITH_BNNECK: True
    NECK_FEAT: after
    POOL_LAYER: GeneralizedMeanPoolingP
    CLS_LAYER: Arcfotmax
    SCALE: 22.213 # s = sqrt(2) * log(num_classes - 1) from AdaCos
    MARGIN: 0.15
    NUM_CLASS: 0
    EMBEDDING_DIM: 512

    PFC:
      ENABALED: True
      SAMPLE_RATE: 0.3

  LOSSES:
    NAME: ("CorssEntropyLoss", )
    CE:
      EPSILON: 0.0
      SCALE: 1.0

  INPUT:
    SIZE_TRAIN: [256, 256]
    SIZE_TEST: [224, 224]

    CROP:
      ENABLED: True
      SIZE: [224, 224]
      SCALE: [0.8, 1.2]
      RATIO: [0.75, 1,33333]

    CJ:
      ENABLED: True
      BRIGHTNESS: 0.3
      CONTRAST: 0.3
      SATURATION: 0.1
      HUE: 0.1
      PROB: 0.8

    FLIP:
      ENABALED: True

  DATALOADER:
    NUM_WORKERS: 4
    SAMPLER_TRAIN: TrainingSampler
    NUM_INSTANCE: 4

  SOLVER:
    FREEZE_ITERS: 0
    AMP:
      ENABLED: True

    OPT: SGD
    SCHED: MultiStepLR
    STEPS: [5, 10, 15]

    BASE_LR: 0.01
    MOMENTUM: 0.95
    NESTEROV: false

    BIAS_LR_FACTOR: 1.
    WEIGHT_DECAY: 0.0005
    WEIGHT_DECAY_BIAS: 0.
    ETA_MIN_LR: 3e-6

    WARMUP_FACTOR: 0.01
    WARMUP_ITERS: 1000

    MAX_EPOCH: 100
    IMG_PER_BATCH: 384

  TEST:
    EVAL_PERIOD: 1000
    IMS_PER_BATCH: 384
    EVALUATOR: RetriEvaluator

  DATASETS:
    TRAIN:
      NAMES:
        - CLASDATASET
      IMAGES:
        - .
      LABELS:
        - /DATA/PATH

    TEST:
      NAMES:
        - RECALL_TEST_DATASET
      IMAGES:
        - .
      LABELS:
        - /DATA_PATH
        
